title: Design an experiment for Mission Space Lab
hero_image: images/banner.png
description: Design an experiment for Mission Space Lab
version: 4
listed: true
copyedit: true
last_tested: "2022-05-19"
steps:
  - title: Introduction
  - title: Develop your idea
    completion:
    - engaged
  - title: Define your measurements
  - title: Test and present your measurements
  - title: Submit your idea
    completion:
    - internal
  - title: What next?
    completion:
    - external
