title: default-project-template
hero_image: images/banner.png
description: default-project-template description
version: 4
listed: false
copyedit: false
last_tested: "2022-05-19"
steps:
  - title: Introduction
  - title: Develop your idea
  - title: Define your measurements
  - title: Test and present your measurements
  - title: Submit your idea
  - title: What next?